name: spotify
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_web_auth_2: ^4.0.2
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

  fonts:
    - family: CircularStd
      fonts:
        - asset: fonts/circular-std-font-family/CircularStd-Black.ttf
        - asset: fonts/circular-std-font-family/CircularStd-Bold.ttf
        - asset: fonts/circular-std-font-family/CircularStd-Book.ttf
        - asset: fonts/circular-std-font-family/CircularStd-Medium.ttf
          style: italic
